open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F
  open Types

  let new_context =
    foreign "fz_new_context"
      ((ptr @@ const alloc_context)
      @-> (ptr @@ const locks_context)
      @-> uint @-> returning @@ ptr context)

  let register_document_handlers =
    foreign "fz_register_document_handlers" (ptr context @-> returning void)

  let open_document =
    foreign "fz_open_document"
      (ptr context @-> string @-> returning @@ ptr document)

  let device_rgb =
    foreign "fz_device_rgb" (ptr context @-> returning @@ ptr colorspace)

  let new_pixmap_from_page_number =
    foreign "fz_new_pixmap_from_page_number"
      (ptr context @-> ptr document @-> int @-> matrix @-> ptr colorspace
     @-> int @-> returning @@ ptr pixmap)

  let save_pixmap_as_png =
    foreign "fz_save_pixmap_as_png"
      (ptr context @-> ptr pixmap @-> string @-> returning void)

  let drop_pixmap =
    foreign "fz_drop_pixmap" (ptr context @-> ptr pixmap @-> returning void)

  let drop_document =
    foreign "fz_drop_document" (ptr context @-> ptr document @-> returning void)

  let drop_context = foreign "fz_drop_context" (ptr context @-> returning void)
end
