open Ctypes
open PosixTypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
  open F
  open Types

  let archive_read_new =
    foreign "archive_read_new" (void @-> returning (ptr archive))

  let archive_read_free =
    foreign "archive_read_free" (ptr archive @-> returning error_code)

  let archive_read_support_filter_all =
    foreign "archive_read_support_filter_all"
      (ptr archive @-> returning error_code)

  let archive_read_support_format_all =
    foreign "archive_read_support_format_all"
      (ptr archive @-> returning error_code)

  let archive_read_open_filename =
    foreign "archive_read_open_filename"
      (ptr archive @-> string @-> size_t @-> returning error_code)

  let archive_read_next_header =
    foreign "archive_read_next_header"
      (ptr archive @-> ptr (ptr archive_entry) @-> returning error_code)

  let archive_entry_pathname_utf8 =
    foreign "archive_entry_pathname_utf8"
      (ptr archive_entry @-> returning @@ string)

  let archive_entry_size =
    foreign "archive_entry_size" (ptr archive_entry @-> returning int64_t)

  let archive_entry_stat =
    foreign "archive_entry_stat"
      (ptr archive_entry @-> returning @@ ptr @@ const stat)

  let archive_entry_strmode =
    foreign "archive_entry_strmode" (ptr archive_entry @-> returning @@ string)

  let archive_entry_mtime =
    foreign "archive_entry_mtime" (ptr archive_entry @-> returning time_t)
end
